### ISSUE TITLE
collect vs map language

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/hash-iteration-collect#2]
Collect vs. map

@pletcher from your md file. if this needs to be elaborated, please do it here.

**Comment by pletcher** [comment]
I think the main thing is that `collect` and `map` are Smalltalk-isms when much of Ruby has moved beyond its (venerable) roots. (See: http://smalltalk.gnu.org/blog/sblinn/list-comprehension-using-select-and-collect)

Map-Reduce has become a by-word (by-phrase?) in its own right, and I think we should remind students once or twice that `collect` is interchangeable with `map` (and `select` with `reduce`).
